# Generated by Django 5.1.9 on 2025-06-26 12:59

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='profile/default.png', upload_to=api.models.profile_path)),
                ('bio', models.TextField()),
                ('is_email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PacketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('prediction', models.CharField(max_length=50)),
                ('flw_duration', models.FloatField()),
                ('total_fwd_packets', models.FloatField()),
                ('total_bwd_packets', models.FloatField()),
                ('fwd_packets_lenght_total', models.FloatField()),
                ('bwd_packets_lenght_total', models.FloatField()),
                ('fwd_packet_length_max', models.FloatField()),
                ('fwd_packet_length_mean', models.FloatField()),
                ('fwd_packet_length_std', models.FloatField()),
                ('bwd_packet_length_max', models.FloatField()),
                ('bwd_packet_length_mean', models.FloatField()),
                ('flow_packets', models.FloatField()),
                ('flow_iat_mean', models.FloatField()),
                ('flow_iat_std', models.FloatField()),
                ('flow_iat_max', models.FloatField()),
                ('fwd_iat_total', models.FloatField()),
                ('fwd_iat_mean', models.FloatField()),
                ('fwd_iat_std', models.FloatField()),
                ('fwd_iat_max', models.FloatField()),
                ('fwd_iat_min', models.FloatField()),
                ('bwd_iat_total', models.FloatField()),
                ('fwd_header_length', models.FloatField()),
                ('bwd_header_length', models.FloatField()),
                ('fwd_packets', models.FloatField()),
                ('bwd_packets', models.FloatField()),
                ('packet_length_max', models.FloatField()),
                ('packet_length_mean', models.FloatField()),
                ('packet_length_std', models.FloatField()),
                ('packet_length_variance', models.FloatField()),
                ('avg_packet_size', models.FloatField()),
                ('avg_fwd_segment_size', models.FloatField()),
                ('avg_bwd_segment_size', models.FloatField()),
                ('subflow_fwd_bytes', models.FloatField()),
                ('subflow_bwd_packets', models.FloatField()),
                ('init_fwd_win_bytes', models.FloatField()),
                ('init_bwd_win_bytes', models.FloatField()),
                ('fwd_act_data_packets', models.FloatField()),
                ('fwd_seg_size_min', models.FloatField()),
                ('active_min', models.FloatField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets', to='api.servermodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
