# Generated by Django 5.2.3 on 2025-07-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_app', '0003_packets_flow_key_packets_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='packets',
            name='total_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='packets',
            name='total_mb',
            field=models.FloatField(default=0.0),
        ),
    ]
